# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://blcxx.github.io
title: Blockchain Coin Project
email: blcxx.github.io
author: BLCXX
description: > # "Write an awesome description for your new site here. 
  Blockchain Coin Project. Blockchain For Everyone.

copyright: 'Copyright &copy; 2017 BLCX Project. All Rights Reserved.'
credits: 'Credits: theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/BLCX_Coin
  - title: github
    url: https://github.com/blcxx/blcx
  - title: Discord
    url: https://discord.gg/fe3Bkmq
